export const BASE_URL = process.env.REACT_APP_BACKEND_API;
export const PRODUCTS_PER_PAGE = 55;
export const PRODUCTS_HOME_PAGE = 50;
export const LIMIT_BUY_PRODUCT = 20;
export const CLOUDINARY_CLOUD_NAME =
  process.env.REACT_APP_CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_UPLOAD_PRESET =
  process.env.REACT_APP_CLOUDINARY_UPLOAD_PRESET;
